### ISSUE TITLE
Additional questions

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/WSBIM1207#11]
@aloriot @KevinUCL could you suggest a total of 4 or 5 additional questions per chapter 2 to 5 that we will add at the end and give students as homework, as discussed last time. 

Feel free to send pull requests or add questions here.

**Comment by kmissault** [comment]
- You’re doing an experiment counting every day how many molds you see in your cell cultures. Create a vector molds `containing` the results of your counts: 1,2,5,8,10
- Let’s assume the experiment started on a Monday. Create a vector `days` containing the days of the week (from Monday to Friday).
- Set the names of `molds` as `days` and extract the number of molds identified on Wednesday,
- Create a data frame molds_study and label variable days as `Time` and variable molds as `Molds_count`.

```
molds <- c(1,2,5,8,10)

days <-  c("Monday","Tuesday","Wednesday","Thursday","Friday")

molds_study <- data.frame("Time" = days, "Molds_count" = molds)
```

**Comment by kmissault** [comment]
# rajouter explication sur le data set

# read file and add delim option or use read_csv2() that uses ; for separator and , for the decimal point (common in European countries)

```
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
beers_data <- read_delim("Data/Beers.csv", ";")
str(beers_data)
```

# Remove NA data

```
beers_data_filter <- beers_data %>%
  filter(!is.na(Consumption))
```


# Does work statue have an impact on beer consumption ?

```
beers_data_filter %>% 
  group_by(Work) %>% 
  summarize(mean_consumption = mean(Consumption))
```


# Do men drink more beers than women ?

```
beers_data_filter %>% 
  group_by(Gender) %>% 
  summarize(mean_consumption = mean(Consumption))
```

# Does working statue have an influence on beer consumption according to gender ?

```
beers_data_filter %>% 
  group_by(Gender, Work) %>% 
  summarize(mean_consumption = mean(Consumption))
```

# Do men drink more than women according to age and work statue ? Plot the graph.

```
mean_age <- beers_data_filter %>%
  group_by(Gender, Age, Work) %>% 
  summarize(mean_consumption = mean(Consumption))

ggplot(data = mean_age, mapping = aes(x = Age, y = mean_consumption, color = Work)) +
  geom_line() +
  facet_wrap(~ Gender) +
  theme_bw()
```

# Demander de changer les titres des axes et de donner un titre et sous-titre à la figure

**Comment by kmissault** [comment]
https://statbel.fgov.be/fr/open-data -> pourrait servir pour un set de donnée plus complexe et donc plus de questions type filtre, group_by, select et exporter une nouvelle table de données bien rangées et filtrées

**Comment by lgatto** [comment]
- Create two vectors `x` and `y` containing the numbers 1 to 10 and 10 to 1 respectively. You can use the `seq` or `:` functions rather than constructing them by hand.
- Check their type. Depending how they were created, they can be integers or doubles.
- Take the sum of each vector and verify they are identical. 
- Sum vectors element-wise, and verify that all results are identical.
- Swap the value or `x` and `y`.
