### ISSUE TITLE
Suggestions: add some table examples in chapter 1

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/WSBIM1207#34]
Add some screenshots of tables, or provide some tables in the first chapter, as students might not be too familiar with tables in the context of research.

**Comment by kmissault** [comment]
Table HTseq count from scRNAseq of TILs CD3+ CD4+ and CD3+ CD8+

<img width="2467" alt="table_htseq_scrnaseq" src="https://user-images.githubusercontent.com/42997930/52349556-1b341500-2a27-11e9-9f99-ec953797355f.png">

**Comment by lgatto** [comment]
- `tab1.png` from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3866554/
- `tab2.png` from qsep paper
- `tab3` from lopit-dc paper

**Comment by lgatto** [comment]
Does anyone have a really ugly example with colours and annotations?

**Comment by kmissault** [comment]
[luminescence.xlsx](https://github.com/UCLouvain-CBIO/WSBIM1207/files/2836821/luminescence.xlsx)

**Comment by kmissault** [comment]
> Does anyone have a really ugly example with colours and annotations?

May be it's a good thing that we don't have this kind of ugly table in our experiments ^^
