### ISSUE TITLE
cannot find GSE96870_intro dataset in package rWSBIM1207

### ISSUE THREAD

**Issue by ManonMartin** [UCLouvain-CBIO/WSBIM1207#59]
when trying to make book, I have to following error message: 

Quitting from lines 7434-7439 (WSBIM1207.Rmd) 
Erreur dans eval(expr, envir, enclos) : objet 'GSE96870_intro' introuvable

(error occuring in chapter Bioinformatics)

**Comment by lgatto** [comment]
Tu dois mettre le package à jour. 

```r
BiocManager::install("UCLouvain-CBIO/rWSBIM1207")
```
